#!/usr/bin/env bash
# Usage: script/test [file] [adapter]... -- [test/unit options]
# Runs the test suite against a local server spawned automatically in a
# thread. After tests are done, the server is shut down.
#
# If filename arguments are given, only those files are run. If arguments given
# are not filenames, they are taken as words that filter the list of files to run.
#
# Examples:
#
#   $ script/test
#   $ script/test test/env_test.rb
#   $ script/test excon typhoeus
#
#   # Run only tests matching /ssl/ for the net_http adapter, with SSL enabled.
#   $ SSL=yes script/test net_http -- -n /ssl/
set -e

if ! grep bundler/setup <<<"$RUBYOPT" >/dev/null; then
  export RUBYOPT="$RUBYOPT -rubygems -rbundler/setup"
fi

port=3999
scheme=http

if [ "$SSL" = "yes" ]; then
  scheme=https
  if [ -z "$SSL_KEY" ] || [ -z "$SSL_FILE" ]; then
    eval "$(script/generate_certs -s)"
  fi
fi

find_test_files() {
  find "$1" -name '*_test.rb'
}

filter_matching() {
  pattern="$1"
  shift
  for line in "$@"; do
    [[ $line == *"$pattern"* ]] && echo "$line"
  done
}

start_server() {
  script/server -p $port >/dev/null 2>&1 &
  echo $!
}

wait_for_server() {
  timeout=$(( `date +%s` + $1 ))
  while true; do
    if lsof -i :$port > /dev/null; then
      break
    elif [ `date +%s` -gt "$timeout" ]; then
      echo "timed out after $1 seconds" >&2
      return 1
    fi
  done
}

filtered=
IFS=$'\n' test_files=($(find_test_files "test"))
declare -a explicit_files

# Process filter arguments:
# - test filenames as taken as-is
# - other words are taken as pattern to match the list of known files against
# - arguments after "--" are forwarded to the ruby process
while [ $# -gt 0 ]; do
  arg="$1"
  shift
  if [ "$arg" = "--" ]; then
    break
  elif [ -f "$arg" ]; then
    filtered=true
    explicit_files[${#explicit_files[@]}+1]="$arg"
  else
    filtered=true
    IFS=$'\n' explicit_files=(
      ${explicit_files[@]}
      $(filter_matching "$arg" "${test_files[@]}" || true)
    )
  fi
done

# If there were filter args, replace test files list with the results
if [ -n "$filtered" ]; then
  if [ ${#explicit_files[@]} -eq 0 ]; then
    echo "Error: no test files match" >&2
    exit 1
  else
    test_files=(${explicit_files[@]})
    echo running "${test_files[@]}"
  fi
fi

# If there are any adapter tests, spin up the HTTP server
if [ -n "$(filter_matching "adapters" "${test_files[@]}")" ]; then
  server_pid=$(start_server)
  wait_for_server 15
  cleanup() {
    kill "$server_pid"
  }
  trap cleanup INT EXIT
  export LIVE="${scheme}://localhost:${port}"
fi

STATUS=0
ruby -Ilib:test -e 'while f=ARGV.shift and f!="--"; load f; end' \
  "${test_files[@]}" -- "$@" || STATUS="$?"

exit $STATUS
